config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get 'users/home'
  get 'users/show'
  get 'rooms/index'
  get 'rooms/show'
  get 'users/register'
  get 'registers/show'
  get 'registers/index'
  get 'rooms/register'
  post 'registers/back' 
  post 'registers/confirmation', to: 'registers#confirmation', as: 'confirmation'
  # post 'registers/complete', to: 'registers#complete', as: 'complete'
  resources :rooms
  resources :users do
    collection do
      get 'search'
    end
  end
  resources :registers
  devise_scope :user do#トップページをログイン画面に
    root 'users#home'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/register.rb
class Register < ApplicationRecord
  belongs_to :room
  # foreign_key :room
  # validates :roomName, presence: true
  # validates :roomAddress, presence: true
  # validates :roomIntroduction, presence: true
  # validates :roomMoney, presence: true
  validates :number, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :number, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validate :start_end_check

  private
  
  def start_end_check
    if end_date.present? || start_date.present?
      if end_date < start_date
        errors.add(:end_date, 'は開始日より前の日を予約することはできません。')
      elsif end_date == start_date
        errors.add(:end_date, 'は開始日より後の日付で選択してください。')
      end
    end
  end
  mount_uploader :image, ImageUploader
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :set_q, only: [:index, :search, :register, :confirmation, :complete, :show, :create, :back]
  def confirmation
    @room = Room.find(params[:id])
    @user = current_user.id
    @register = Register.new(params.require(:register).permit(:roomName, :user_id, :roomIntroduction, :roomMoney, :roomAddress, :registerImage, :end_date, :start_date, :number, :room_id ))
    render("rooms/register") if @register.invalid?
	end
  def back
    @room = Room.find(params[:id])
    @user = current_user.id
		@register = Register.new(params.require(:register).permit(:roomName, :user_id, :roomIntroduction, :roomMoney, :roomAddress, :registerImage, :end_date, :start_date, :number, :room_id ))
		render("rooms/register")
	end
  def create
    @user = current_user.id
    @register = Register.new(params.require(:register).permit(:roomName, :user_id, :roomIntroduction, :roomMoney, :roomAddress, :registerImage, :end_date, :start_date, :number, :room_id ))
    if @register.save
      redirect_to registers_show_path(id: @register.id) 
    else 
      flash[:notice] = "失敗"
       redirect_to rooms_register_path(id: @register.room.id)
    end
    # binding.pry
  end
  def index 
    @registers = Register.all.order(created_at: :desc) 
    @user = current_user.id
  end
  def show
    # binding.pry
    @user = current_user.id
    @register = Register.find(params[:id])
  end
  def complete
    # binding.pry
    @user = current_user.id
    @register = Register.find(params[:id])
  end
  private
  def register_params
    @user = current_user.id
    params.require(:register).permit(:roomName, :user_id, :roomIntroduction, :roomMoney, :roomAddress, :registerImage, :email, :end_date, :start_date, :number, :back)
  end
  def search
    @results = @q.result
    # @user = current_user.id
  end
  private

  def set_q
    @q = Room.ransack(params[:q])
  end
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/views/registers/confirmation.html.erb
<header>
  <div class='all_header'>
    <a><img alt="サイトロゴ画像" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"></a>
    <div class='text_form'>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomAddress_cont, class:"simple_search" %>
        <i class="fas fa-map-marker-alt"></i>
      <% end %>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomName_cont, class:"simple_search" %>
        <i class="fa fa-search" aria-hidden="true"></i>
      <% end %>
    </div>
    <div class='user_name'><%= @current_user.name%></div>
    <% if @current_user.image.attached? %>
      <%= image_tag @current_user.image, class: "user_icon"%>
    <% else %>
      <%= image_tag 'no_image', class: "user_icon" %>
    <% end %>
  </div>
</header>
<ul class="menu_ul">
  <li class="menu_li"><%= link_to 'ルーム登録', users_register_path %></li>
  <li class="menu_li"><%= link_to '予約済みルーム一覧', registers_index_path %></li>
  <li class="menu_li"><%= link_to '登録済みルーム一覧', users_path %></li>
  <li class="menu_li"><%= link_to '設定', edit_user_path(id: @user) %></li>
  <li class="menu_li"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete%></li>
</ul>

<table class='account_table'>
  <tr>
    <td>¥<%= @register.roomMoney %>/日</td>
  </tr>
  <tr>
    <th>開始日</th>
    <td><%= @register.start_date %></td>
  </tr>
  <tr>
    <th>終了日</th>
    <td><%= @register.end_date %></td>
  </tr>
  <tr>
    <th>使用日数</th>
    <td class = 'totalDate'><%= (@register.end_date - @register.start_date) %></td>
  </tr>
  <tr>
    <th>人数</th>
    <td><%= @register.number %></td>
  </tr>
  <tr>
    <th>合計金額</th>
    <td class="totalMoney"><%= ((@register.end_date - @register.start_date) * (@register.roomMoney)) * (@register.number) %></td>
  </tr>
</table>

<%= form_with model: @register do |form| %>
	<%= form.hidden_field :roomName %>
	<%= form.hidden_field :roomAddress %>
	<%= form.hidden_field :roomIntroduction %>
  <%= form.hidden_field :roomMoney %>
  <%= form.hidden_field :start_date %>
	<%= form.hidden_field :end_date %>
  <%= form.hidden_field :roomMoney %>
  <%= form.hidden_field :number %>
  <%= form.hidden_field :registerImage %>
  <%= form.hidden_field :user_id %>
  <%= form.hidden_field :room_id %>
	<%= form.submit '送信する' %>
<% end %>
<%= form_for @register, method: :post, url: registers_back_url(id: @room.id) do |form| %>
	<%= form.hidden_field :roomName %>
	<%= form.hidden_field :roomAddress %>
	<%= form.hidden_field :roomIntroduction %>
  <%= form.hidden_field :roomMoney %>
  <%= form.hidden_field :start_date %>
	<%= form.hidden_field :end_date %>
  <%= form.hidden_field :roomMoney %>
  <%= form.hidden_field :number %>
  <%= form.hidden_field :registerImage %>
  <%= form.hidden_field :user_id %>
  <%= form.hidden_field :room_id %>
	<%= form.submit '入力画面に戻る' %>
<% end %>
<script>
$(document).ready(function() {
  let date = $('.totalDate').text().replace('/1', '');
    $('.totalDate').text(date);
  let money = $('.totalMoney').text().replace('/1', '');
    $('.totalMoney').text(money)
  });
</script>

app/views/registers/index.html.erb
<header>
  <div class='all_header'>
    <a><img alt="サイトロゴ画像" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"></a>
    <div class='text_form'>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomAddress_cont, class:"simple_search" %>
        <i class="fas fa-map-marker-alt"></i>
      <% end %>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomName_cont, class:"simple_search" %>
        <i class="fa fa-search" aria-hidden="true"></i>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class='user_name'><%= @current_user.name%></div>
      <% if @current_user.image.attached? %>
        <%= image_tag @current_user.image, class: "user_icon"%>
      <% else %>
        <%= image_tag 'no_image', class: "user_icon" %>
      <% end %>
    <% else %>
      <%= link_to 'ログイン', new_user_session_path, class:'session' %>
      <%= link_to '登録する', new_user_registration_path, class:'registration'%>
    <% end %>
  </div>
</header>
<ul class="menu_ul">
  <li class="menu_li"><%= link_to 'ルーム登録', users_register_path %></li>
  <li class="menu_li"><%= link_to '予約済みルーム一覧', registers_index_path %></li>
  <li class="menu_li"><%= link_to '登録済みルーム一覧', users_path %></li>
  <li class="menu_li"><%= link_to '設定', edit_user_path(id: @user) %></li>
  <li class="menu_li"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete%></li>
</ul>
<h3>予約済みルーム一覧</h3>
<table>
  <thead>
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>合計料金</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>予約確定日時</th>
    </tr>
  </thead>

  <tbody>
    <% @registers.each do |register| %>
      <tr>
        <td><%= image_tag register.registerImage if register.registerImage? %></td>
        <td><%= link_to register.roomName, rooms_register_path(id: register.room.id) %></td>
        <td><%= register.roomIntroduction %></td>
        <td><%= register.roomMoney %></td>
        <td><%= register.start_date.to_s(:yeardate) %></td>
        <td><%= register.end_date.to_s(:yeardate) %></td>
        <td><%= register.created_at.to_s(:datetime_jp) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/registers/show.html.erb
<header>
  <div class='all_header'>
    <a><img alt="サイトロゴ画像" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"></a>
    <div class='text_form'>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomAddress_cont, class:"simple_search" %>
        <i class="fas fa-map-marker-alt"></i>
      <% end %>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomName_cont, class:"simple_search" %>
        <i class="fa fa-search" aria-hidden="true"></i>
      <% end %>
    </div>
    <div class='user_name'><%= @current_user.name%></div>
    <% if @current_user.image.attached? %>
      <%= image_tag @current_user.image, class: "user_icon"%>
    <% else %>
      <%= image_tag 'no_image', class: "user_icon" %>
    <% end %>
  </div>
</header>
<ul class="menu_ul">
  <li class="menu_li"><%= link_to 'ルーム登録', users_register_path %></li>
  <li class="menu_li"><%= link_to '予約済みルーム一覧', registers_index_path %></li>
  <li class="menu_li"><%= link_to '登録済みルーム一覧', users_path %></li>
  <li class="menu_li"><%= link_to '設定', edit_user_path(id: current_user) %></li>
  <li class="menu_li"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete%></li>
</ul>
<div class='account_show'>
  <div class='account_page'>
      <table class='account_table'>
        <tr>
          <th>予約した部屋</th>
          <td><%= @register.roomName %></td>
        </tr>
        <tr>
          <th>開始日</th>
          <td><%= @register.start_date %></td>
        </tr>
        <tr>
          <th>終了日</th>
          <td><%= @register.end_date %></td>
        </tr>
        <tr>
          <th>終了日</th>
          <td><%= @register.roomMoney %></td>
        </tr>
      </table>
  </div>
</div>