config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get 'users/home'
  get 'users/show'
  get 'rooms/index'
  get 'rooms/show'
  get 'users/register'
  get 'registers/show'
  get 'registers/index'
  get 'rooms/register'
  post 'registers/back' 
  post 'registers/confirmation', to: 'registers#confirmation', as: 'confirmation'
  # post 'registers/complete', to: 'registers#complete', as: 'complete'
  resources :rooms
  resources :users do
    collection do
      get 'search'
    end
  end
  resources :registers
  devise_scope :user do#トップページをログイン画面に
    root 'users#home'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms
  has_many :registers
  has_one_attached :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :set_q, only: [:new, :search, :create, :edit, :update]
  
  # skip_before_action :verify_authenticity_token, :only => :create
  # protect_from_forgery with: :null_session
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  def after_update_path_for(resource)
    # 自分で設定した「マイページ」へのパス
    edit_user_path(@user)
  end
  def after_sign_up_path_for(resource)
    users_show_path(id: @user.id)
  end
  def search
    @results = @q.result
  end
  private

  def set_q
    @q = Room.ransack(params[:q])
  end
  # def after_sign_up_path_for(resource)
  #   user_path(id: @user)
  # end
  # def after_sign_out_path_for(resource)
  #   users_home_path # ログアウト後に遷移するpathを設定
  # end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :set_q, only: [:new, :search]
  def after_sign_in_path_for(resource)
    users_show_path(id: @user.id)
  end
  def search
    @results = @q.result
  end
  private

  def set_q
    @q = Room.ransack(params[:q])
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!, except: :home
  before_action :set_q, only: [:home, :edit, :update, :show, :index, :search, :register, :sign_up, :sign_in]
  def register
    @user = current_user.id
    @room = Room.new
  end

  def index
    @rooms = Room.all
    @rooms.where!(user_id: current_user.id)
    @user = current_user.id
  end
  def edit
    @q = Room.ransack(params[:q])
    @user = User.find(params[:id])
  end
  def show
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(params.require(:user).permit(:name, :image, :introduction, :iconImage))
      flash[:notice] = "ユーザーIDが「#{@user.id}」の情報を更新しました"
      redirect_to request.referer
    else
      render "edit"
    end
  end
  def home 
    @rooms = Room.all
  end
  def search
    @results = @q.result
    if current_user
      @user = current_user.id
    end
  end
  private

  def set_q
    @q = Room.ransack(params[:q])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<header>
  <div class='all_header'>
    <a><img alt="サイトロゴ画像" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"></a>
    <div class='text_form'>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomAddress_cont, class:"simple_search" %>
        <i class="fas fa-map-marker-alt"></i>
      <% end %>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomName_cont, class:"simple_search" %>
        <i class="fa fa-search" aria-hidden="true"></i>
      <% end %>
    </div>
    <div class='user_name'><%= @user.name%></div>
    <% if @user.image.attached? %>
      <%= image_tag @user.image, class: "user_icon"%>
    <% else %>
      <%= image_tag 'no_image', class: "user_icon" %>
    <% end %>
  </div>
</header>
<ul class="menu_ul">
  <li class="menu_li"><%= link_to 'ルーム登録', users_register_path %></li>
  <li class="menu_li"><%= link_to '予約済みルーム一覧', registers_index_path %></li>
  <li class="menu_li"><%= link_to '登録済みルーム一覧', users_path %></li>
  <li class="menu_li"><%= link_to '設定', edit_user_path(id: @user) %></li>
  <li class="menu_li"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete%></li>
</ul>
<div class="profile">
  <%= render "shared/setting" %>
  <%= render "devise/shared/error_messages", resource: @user %>
  <%= form_with model: @user do |f| %>
    <table>
      <td><% if @user.image.attached? %>
        <%= image_tag @user.image, class: "user_icon" %>
      <% else %>
        <%= image_tag 'no_image', class: "user_icon" %>
      <% end %></td>
      <tr>
        <th><%= f.label :image, "アイコン画像" %></th>
        <td><%= f.file_field :image, class: "room-image" %></td>
      </tr>
      <tr>
        <th><%= f.label :name, "名前" %></th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th><%= f.label :introduction, "自己紹介" %></th>
        <td><%= f.text_field :introduction %></td>
      </tr>
    </table>
    <div>
      <ul>
        <li><%= f.submit "更新" %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/users/home.html.erb
<header>
  <div class='all_header'>
    <a><img alt="サイトロゴ画像" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"></a>
    <div class='text_form'>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomAddress_cont, class:"simple_search" %>
        <i class="fas fa-map-marker-alt"></i>
      <% end %>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomName_cont, class:"simple_search" %>
        <i class="fa fa-search" aria-hidden="true"></i>
      <% end %>
    </div>
    <%= link_to 'ログイン', new_user_session_path, class:'session' %>
    <%= link_to '登録する', new_user_registration_path, class:'registration'%>
  </div>
</header>
<div class='top_page'>
  <div class='form_page'>
    <%= tag.p class:"title_potepan" do %>Potepan Shareでまだ体験したことのない旅をしよう<% end %>
    <div class='form'>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.label :roomAddress, 'エリア' %>
        <br>
        <%= f.search_field :roomAddress_cont, :placeholder => "東京", class:"form_search" %>
        <br>
        <%= f.submit '検索する',class:'sumbit_search' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<header>
  <div class='all_header'>
    <a><img alt="サイトロゴ画像" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"></a>
    <div class='text_form'>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomAddress_cont, class:"simple_search" %>
        <i class="fas fa-map-marker-alt"></i>
      <% end %>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomName_cont, class:"simple_search" %>
        <i class="fa fa-search" aria-hidden="true"></i>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class='user_name'><%= @current_user.name%></div>
      <% if @current_user.image.attached? %>
        <%= image_tag @current_user.image, class: "user_icon"%>
      <% else %>
        <%= image_tag 'no_image', class: "user_icon" %>
      <% end %>
    <% else %>
      <%= link_to 'ログイン', new_user_session_path, class:'session' %>
      <%= link_to '登録する', new_user_registration_path, class:'registration'%>
    <% end %>
  </div>
</header>
<ul class="menu_ul">
  <li class="menu_li"><%= link_to 'ルーム登録', users_register_path %></li>
  <li class="menu_li"><%= link_to '予約済みルーム一覧', registers_index_path %></li>
  <li class="menu_li"><%= link_to '登録済みルーム一覧', users_path %></li>
  <li class="menu_li"><%= link_to '設定', edit_user_path(id: @user) %></li>
  <li class="menu_li"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete%></li>
</ul>
<h3>登録済みルーム一覧</h3>
<table>
  <thead>
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>料金</th>
      <th>作成日</th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= image_tag room.image.url if room.image? %></td>
        <td><%= link_to room.roomName, rooms_register_path(id: room.id), method: :get %></td>
        <td><%= room.roomIntroduction %></td>
        <td><%= room.roomMoney %></td>
        <td><%= room.created_at.to_s(:yeardate) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/register.html.erb
<header>
  <div class='all_header'>
    <a><img alt="サイトロゴ画像" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"></a>
    <div class='text_form'>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomAddress_cont, class:"simple_search" %>
        <i class="fas fa-map-marker-alt"></i>
      <% end %>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomName_cont, class:"simple_search" %>
        <i class="fa fa-search" aria-hidden="true"></i>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class='user_name'><%= @current_user.name%></div>
      <% if @current_user.image.attached? %>
        <%= image_tag @current_user.image, class: "user_icon"%>
      <% else %>
        <%= image_tag 'no_image', class: "user_icon" %>
      <% end %>
    <% else %>
      <%= link_to 'ログイン', new_user_session_path, class:'session' %>
      <%= link_to '登録する', new_user_registration_path, class:'registration'%>
    <% end %>
  </div>
</header>
<ul class="menu_ul">
  <li class="menu_li"><%= link_to 'ルーム登録', users_register_path %></li>
  <li class="menu_li"><%= link_to '予約済みルーム一覧', registers_index_path %></li>
  <li class="menu_li"><%= link_to '登録済みルーム一覧', users_path %></li>
  <li class="menu_li"><%= link_to '設定', edit_user_path(id: @user) %></li>
  <li class="menu_li"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete%></li>
</ul>
 <h3>ルーム情報登録</h3>
 <%= form_with model: @room, local: true do |f| %>
   <%= render "devise/shared/error_messages", resource: f.object  %>
   <table>
     <tr>
       <th><%= f.label :roomName, "ルーム名" %></th>
       <td><%= f.text_field :roomName, class:"room-name" %></td>
     </tr>
     <tr>
       <th><%= f.label :roomIntroduction, "ルーム紹介" %></th>
       <td><%= f.text_area :roomIntroduction, class:"room-introduction" %></td>
     </tr>
     <tr>
       <th><%= f.label :roomMoney, "料金" %></th>
       <td><%= f.number_field :roomMoney, class:"room-money" %></td>
     </tr>
     <tr>
       <th><%= f.label :roomAddress, "住所" %></th>
       <td><%= f.text_field :roomAddress, class:"room-address" %></td>
     </tr>
     <tr>
       <th><%= f.label :image, "ルーム画像" %></th>
			 <td><%= f.file_field :image, accept: "image/*" %></td>
     </tr>
   </table>
   <%= f.hidden_field :user_id, value: @current_user.id %>
   <%= f.hidden_field :email, value: @current_user.email %>
   <%= f.hidden_field :password_confirmation, value: @current_user.encrypted_password %>
    <div>
     <ul>
       <li><%= f.submit "投稿を完了する"%></li>
     </ul>
    </div>
 <% end %>

app/views/users/search.html.erb
<header>
  <div class='all_header'>
    <a><img alt="サイトロゴ画像" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"></a>
    <div class='text_form'>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomAddress_cont, class:"simple_search" %>
        <i class="fas fa-map-marker-alt"></i>
      <% end %>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomName_cont, class:"simple_search" %>
        <i class="fa fa-search" aria-hidden="true"></i>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class='user_name'><%= @current_user.name%></div>
      <% if @current_user.image.attached? %>
        <%= image_tag @current_user.image, class: "user_icon"%>
      <% else %>
        <%= image_tag 'no_image', class: "user_icon" %>
      <% end %>
      <ul class="menuUl">
        <li class="menu_li"><%= link_to 'ルーム登録', users_register_path %></li>
        <li class="menu_li"><%= link_to '予約済みルーム一覧', registers_index_path %></li>
        <li class="menu_li"><%= link_to '登録済みルーム一覧', users_path %></li>
        <li class="menu_li"><%= link_to '設定', edit_user_path(id: @user) %></li>
        <li class="menu_li"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete%></li>
      </ul>
    <% else %>
      <%= link_to 'ログイン', new_user_session_path, class:'session' %>
      <%= link_to '登録する', new_user_registration_path, class:'registration'%>
    <% end %>
  </div>
</header>
<table class="search_table">
  <tbody class="search_tbody">
    <% @results.each do |room| %>
      <tr class="seach_table" onclick='window.location="<%= rooms_show_path(id: room.id) %>"' role="link"h>
        <td class="room_td">
          <% if room.image.url %>
            <%= image_tag room.image.url if room.image? %>
          <% else %>
            <%= image_tag 'no_image' %>
          <% end %>
        </td>
        <td class="room_td"><%= room.roomName %></td>
        <td class="room_td"><%= room.roomAddress %></td>
        <td class="room_td"><%= room.roomMoney %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Top', users_path %>

app/views/users/show.html.erb
<header>
  <div class='all_header'>
    <a><img alt="サイトロゴ画像" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"></a>
    <div class='text_form'>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomAddress_cont, class:"simple_search" %>
        <i class="fas fa-map-marker-alt"></i>
      <% end %>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomName_cont, class:"simple_search" %>
        <i class="fa fa-search" aria-hidden="true"></i>
      <% end %>
    </div>
    <div class='user_name'><%= @user.name%></div>
    <% if @user.image.attached? %>
      <%= image_tag @user.image, class: "user_icon"%>
    <% else %>
      <%= image_tag 'no_image', class: "user_icon" %>
    <% end %>
  </div>
</header>
<ul class="menu_ul">
  <li class="menu_li"><%= link_to 'ルーム登録', users_register_path %></li>
  <li class="menu_li"><%= link_to '予約済みルーム一覧', registers_index_path %></li>
  <li class="menu_li"><%= link_to '登録済みルーム一覧', users_path %></li>
  <li class="menu_li"><%= link_to '設定', edit_user_path(id: @user) %></li>
  <li class="menu_li"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete%></li>
</ul>
<div class='account_show'>
  <%= render "shared/setting" %>
  <div class='account_page'>
      <h3>プロフィール</h3>
      <table class='account_table'>
        <tr>
          <th>メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th>パスワード</th>
          <td>**********</td>
        </tr>
      </table>
      <%= link_to '編集', :edit_user_registration %>
  </div>
</div>