config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get 'users/home'
  get 'users/show'
  get 'rooms/index'
  get 'rooms/show'
  get 'users/register'
  get 'registers/show'
  get 'registers/index'
  get 'rooms/register'
  post 'registers/back' 
  post 'registers/confirmation', to: 'registers#confirmation', as: 'confirmation'
  # post 'registers/complete', to: 'registers#complete', as: 'complete'
  resources :rooms
  resources :users do
    collection do
      get 'search'
    end
  end
  resources :registers
  devise_scope :user do#トップページをログイン画面に
    root 'users#home'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_header.html.erb
<header>
  <a><img alt="サイトロゴ画像" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"></a>
  <span class="menu">メニュー</span>
  <ul class="menu_ul">
    <li class="menu_li"><%= link_to 'ルーム登録', users_register_path %></li>
    <li class="menu_li"><%= link_to '予約済みルーム一覧', registers_index_path %></li>
    <li class="menu_li"><%= link_to '登録済みルーム一覧', users_path %></li>
    <li class="menu_li"><a href="#">設定</a></li>
    <li class="menu_li"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete%></li>
  </ul>
  <% if @user.image.attached? %>
    <%= image_tag @user.image, class: "user_icon"%>
  <% else %>
    <%= image_tag 'no_image' %>
  <% end %>
</header>

app/views/shared/_home.html.erb
<header>
  <div class='all_header'>
    <a><img alt="サイトロゴ画像" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"></a>
    <div class='text_form'>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomAddress_cont, class:"simple_search" %>
        <i class="fas fa-map-marker-alt"></i>
      <% end %>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomName_cont, class:"simple_search" %>
        <i class="fa fa-search" aria-hidden="true"></i>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class='user_name'><%= @current_user.name%></div>
      <% if @current_user.image.attached? %>
        <%= image_tag @current_user.image, class: "user_icon"%>
      <% else %>
        <%= image_tag 'no_image', class: "user_icon" %>
      <% end %>
      <ul class="menuUl">
        <li class="menu_li"><%= link_to 'ルーム登録', users_register_path %></li>
        <li class="menu_li"><%= link_to '予約済みルーム一覧', registers_index_path %></li>
        <li class="menu_li"><%= link_to '登録済みルーム一覧', users_path %></li>
        <li class="menu_li"><%= link_to '設定', edit_user_path(id: @user) %></li>
        <li class="menu_li"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete%></li>
      </ul>
    <% else %>
      <%= link_to 'ログイン', new_user_session_path, class:'session' %>
      <%= link_to '登録する', new_user_registration_path, class:'registration'%>
    <% end %>
  </div>
</header>

app/views/shared/_room.html.erb
<div class="select_setting">
  <ul>
    <li><%= link_to "基本情報", new_user_path %></li>
  </ul>
</div>

app/views/shared/_setting.html.erb
<div class="select_setting">
  <ul>
    <li><%= link_to "アカウント", edit_user_path(id: @user.id) %></li>
    <li><%= link_to "プロフィール", users_show_path(id: @user.id) %></li>
  </ul>
</div>