config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get 'users/home'
  get 'users/show'
  get 'rooms/index'
  get 'rooms/show'
  get 'users/register'
  get 'registers/show'
  get 'registers/index'
  get 'rooms/register'
  post 'registers/back' 
  post 'registers/confirmation', to: 'registers#confirmation', as: 'confirmation'
  # post 'registers/complete', to: 'registers#complete', as: 'complete'
  resources :rooms
  resources :users do
    collection do
      get 'search'
    end
  end
  resources :registers
  devise_scope :user do#トップページをログイン画面に
    root 'users#home'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :registers
  # foreign_key: user_id
  mount_uploader :image, ImageUploader
  validates :roomMoney, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :roomName, presence: true
  validates :roomAddress, presence: true
  validates :roomIntroduction, presence: true
  validates :roomMoney, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # before_action :authenticate_user!, except: :show
  # before_action :permit_params, except: :new
  def register
    @room = Room.find(params[:id])
    @user = current_user.id
    @register = Register.new
  end
  def index
    @registers = Register.all
    @user = current_user.id
  end
  def new
    @user = current_user.id
    # @user = User.find(params[:id])
    @room = Room.new
  end
  def create
    @user = current_user.id
    @room = Room.new(params.require(:room).permit(:roomName, :user_id, :roomIntroduction, :roomMoney, :roomAddress, :image, :email, :encrypted_password, :register ))
    begin @room.save!
      redirect_to rooms_register_path(id: @room.id)
    rescue ActiveRecord::RecordInvalid => e
      flash[:notice] = "失敗"
      render("users/register")
    end
  end

  def edit
    @rooms = Room.all
  end
  before_action :set_q, only: [:show, :search, :register, :create, :index]
  def show
    @room = Room.find(params[:id])
  end
  def search
    @results = @q.result
  end
  private

  def set_q
    @q = Room.ransack(params[:q])
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<header>
  <a><img alt="サイトロゴ画像" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"></a>
  <span class="menu">メニュー</span>
  <ul class="menu_ul">
    <li class="menu_li"><%= link_to 'ルーム登録', users_register_path %></li>
    <li class="menu_li"><%= link_to '予約済みルーム一覧', registers_index_path %></li>
    <li class="menu_li"><%= link_to '登録済みルーム一覧', users_path %></li>
    <li class="menu_li"><%= link_to '設定', edit_user_path(id: @user) %></li>
    <li class="menu_li"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete%></li>
  </ul>
  <% if @current_user.image.attached? %>
    <%= image_tag @current_user.image, class: "user_icon"%>
  <% else %>
    <%= image_tag 'no_image' %>
  <% end %>
</header>
<h3>ユーザー情報一覧</h3>
<table>
  <thead>
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>料金</th>
      <th>作成日</th>
    </tr>
  </thead>
  <tbody>
    <% @user.rooms.each do |room| %>
      <tr>
        <td><%= image_tag @room.image.url if @room.image? %></td>
        <td><%= room.roomName %></td>
        <td><%= room.roomIntroduction %></td>
        <td><%= room.roomMoney %></td>
        <td><%= room.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/register.html.erb
<header>
  <div class='all_header'>
    <a><img alt="サイトロゴ画像" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"></a>
    <div class='text_form'>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomAddress_cont, class:"simple_search" %>
        <i class="fas fa-map-marker-alt"></i>
      <% end %>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomName_cont, class:"simple_search" %>
        <i class="fa fa-search" aria-hidden="true"></i>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class='user_name'><%= @current_user.name%></div>
      <% if @current_user.image.attached? %>
        <%= image_tag @current_user.image, class: "user_icon"%>
      <% else %>
        <%= image_tag 'no_image', class: "user_icon" %>
      <% end %>
    <% else %>
      <%= link_to 'ログイン', new_user_session_path, class:'session' %>
      <%= link_to '登録する', new_user_registration_path, class:'registration'%>
    <% end %>
  </div>
</header>
<ul class="menu_ul">
  <li class="menu_li"><%= link_to 'ルーム登録', users_register_path %></li>
  <li class="menu_li"><%= link_to '予約済みルーム一覧', registers_index_path(@room) %></li>
  <li class="menu_li"><%= link_to '登録済みルーム一覧', users_path %></li>
  <li class="menu_li"><%= link_to '設定', edit_user_path(id: @user) %></li>
  <li class="menu_li"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete%></li>
</ul>
<div class='account_show'>
  <div class='account_page'>
  <h3>プロフィール</h3>
  <table class='account_table'>
    <tr>
      <th>ルーム名</th>
      <td><%= @room.roomName %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td><%= @room.roomAddress %></td>
    </tr>
    <tr>
      <th>ルーム紹介</th>
      <td><%= @room.roomIntroduction %></td>
    </tr>
    <tr>
      <th>料金</th>
      <td class= 'room_money'><%= @room.roomMoney %>/1</td>
    </tr>
    <tr>
      <th>画像</th>
      <td><%= image_tag @room.image.url if @room.image? %></td>
    </tr>
  </table>
      <div>
        <%= form_with model: @register, url: confirmation_path(id: @room.id) do |f| %>
        <%= render "devise/shared/error_messages", resource: f.object  %>
        <div>¥<%= @room.roomMoney %>/日</div>
        <table>
          <tr>
            <th><%= f.label :start_date, "開始日" %></th>
            <td><%= f.date_field :start_date, class:"order-date-form", min: Date.current %></td>
          </tr>
          <tr>
            <th><%= f.label :end_date, "終了日" %></th>
            <td><%= f.date_field :end_date, class:"order-date-form", min: Date.current %></td>
          </tr>
          <tr>
            <th><%= f.label :number, "人数" %></th>
            <td><%= f.number_field :number, class:"posts-content" %></td>
          </tr>
        </table>
          <%= f.hidden_field :registerImage, value: @room.image.url if @room.image? %>
          <%= f.hidden_field :user_id, value: @room.user_id %>
          <%= f.hidden_field :roomName, value: @room.roomName %>
          <%= f.hidden_field :roomIntroduction, value: @room.roomIntroduction %>
          <%= f.hidden_field :roomMoney, value: @room.roomMoney %>
          <%= f.hidden_field :room_id, value: @room.id %>
        <ul>
          <li><%= f.submit "予約" %></li>
        </ul>
        <% end %>
      </div>
  </div>
</div>
<script>
$(document).ready(function() {
  let money = $('.room_money').text().replace('/1', '');
    $('.room_money').text(money);
  });
</script>

app/views/rooms/show.html.erb
<header>
  <div class='all_header'>
    <a><img alt="サイトロゴ画像" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"></a>
    <div class='text_form'>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomAddress_cont, class:"simple_search" %>
        <i class="fas fa-map-marker-alt"></i>
      <% end %>
      <%= search_form_for @q, url: search_users_path do |f| %>
        <%= f.search_field :roomName_cont, class:"simple_search" %>
        <i class="fa fa-search" aria-hidden="true"></i>
      <% end %>
    </div>
    <%= link_to 'ログイン', new_user_session_path, class:'session' %>
    <%= link_to '登録する', new_user_registration_path, class:'registration'%>
  </div>
</header>
<div class='account_show'>
  <div class='account_page'>
  <h3>プロフィール</h3>
  <table class='account_table'>
    <tr>
      <th>ルーム名</th>
      <td><%= @room.roomName %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td><%= @room.roomAddress %></td>
    </tr>
    <tr>
      <th>ルーム紹介</th>
      <td><%= @room.roomIntroduction %></td>
    </tr>
    <tr>
      <th>料金</th>
      <td><%= @room.roomMoney %>/1</td>
    </tr>
    <tr>
      <th>画像</th>
      <td><%= image_tag @room.image.url if @room.image? %></td>
    </tr>
  </table>
      <div>
        <%= form_with model: @register, url: confirmation_path(@register) do |f| %>
        <div>¥<%= @room.roomMoney %>/日</div>
        <table>
          <tr>
            <th><%= f.label :start_date, "開始日" %></th>
            <td><%= f.date_field :start_date, class:"order-date-form", min: Date.current %></td>
          </tr>
          <tr>
            <th><%= f.label :end_date, "終了日" %></th>
            <td><%= f.date_field :end_date, class:"order-date-form", min: Date.current %></td>
          </tr>
          <tr>
            <th><%= f.label :number, "人数" %></th>
            <td><%= f.number_field :number, class:"posts-content" %></td>
          </tr>
        </table>
        <ul>
          <li><%= link_to 'ログイン', :new_user_session %></li>
        </ul>
        <% end %>
      </div>
  </div>
</div>